import { TimelinePhase, ContractorStatus } from './timeframe.model';

function d(year: number, month: number, day: number): Date {
  return new Date(year, month - 1, day);
}

function pickStatus(progress: number, end: Date): ContractorStatus {
  const today = new Date();
  if (progress >= 100) return 'completed';
  if (progress === 0) return 'not_started';
  if (end < today && progress < 100) return 'delayed';
  return 'in_progress';
}

export function buildMockTimeframe(projectId: string): TimelinePhase[] {
  const phases: TimelinePhase[] = [
    {
      id: 1,
      name: 'مرحلة التحضير والتجهيز',
      description: 'الأعمال التمهيدية والتراخيص',
      order: 1,
      startDate: d(2026, 1, 5),
      endDate: d(2026, 2, 20),
      progress: 100,
      expanded: true,
      contractors: [
        {
          id: 101,
          name: 'مقاول التراخيص',
          contractorType: 'استشاري',
          zone: 'المكاتب',
          startDate: d(2026, 1, 5),
          endDate: d(2026, 1, 25),
          progress: 100,
          status: 'completed',
          amount: 45000,
          totalPayments: 45000,
          notes: 'تم استخراج جميع التراخيص اللازمة من الجهات المعنية.',
        },
        {
          id: 102,
          name: 'مقاول المسح والتربة',
          contractorType: 'مسح',
          zone: 'الموقع',
          startDate: d(2026, 1, 15),
          endDate: d(2026, 2, 10),
          progress: 100,
          status: 'completed',
          amount: 32000,
          totalPayments: 32000,
          dependsOnIds: [101],
        },
        {
          id: 103,
          name: 'مقاول السياج والتسوير',
          contractorType: 'تأسيس موقع',
          zone: 'محيط الموقع',
          startDate: d(2026, 2, 1),
          endDate: d(2026, 2, 20),
          progress: 100,
          status: 'completed',
          amount: 28000,
          totalPayments: 28000,
        },
      ],
    },
    {
      id: 2,
      name: 'مرحلة الحفر والأساسات',
      description: 'حفر الأساسات والقواعد',
      order: 2,
      startDate: d(2026, 2, 15),
      endDate: d(2026, 4, 30),
      progress: 78,
      expanded: true,
      contractors: [
        {
          id: 201,
          name: 'مقاول الحفر',
          contractorType: 'حفر',
          zone: 'الموقع - القطاع أ',
          startDate: d(2026, 2, 15),
          endDate: d(2026, 3, 25),
          progress: 100,
          status: 'completed',
          amount: 120000,
          totalPayments: 120000,
        },
        {
          id: 202,
          name: 'مقاول العزل المائي',
          contractorType: 'عزل',
          zone: 'الموقع - القطاع أ',
          startDate: d(2026, 3, 10),
          endDate: d(2026, 4, 5),
          progress: 95,
          status: 'in_progress',
          amount: 88000,
          totalPayments: 70000,
          dependsOnIds: [201],
          notes: 'متبقي أعمال العزل في الجهة الشمالية.',
        },
        {
          id: 203,
          name: 'مقاول الخرسانة',
          contractorType: 'خرسانة',
          zone: 'الموقع - القطاع أ',
          startDate: d(2026, 3, 20),
          endDate: d(2026, 4, 30),
          progress: 60,
          status: 'in_progress',
          amount: 215000,
          totalPayments: 130000,
          dependsOnIds: [202],
        },
      ],
    },
    {
      id: 3,
      name: 'مرحلة الهيكل الإنشائي',
      description: 'الأعمدة والأسقف والجدران الحاملة',
      order: 3,
      startDate: d(2026, 4, 15),
      endDate: d(2026, 8, 10),
      progress: 35,
      expanded: true,
      contractors: [
        {
          id: 301,
          name: 'مقاول الحديد',
          contractorType: 'حديد تسليح',
          zone: 'الهيكل',
          startDate: d(2026, 4, 15),
          endDate: d(2026, 6, 30),
          progress: 55,
          status: 'in_progress',
          amount: 340000,
          totalPayments: 180000,
        },
        {
          id: 302,
          name: 'مقاول البلوك والبناء',
          contractorType: 'بناء',
          zone: 'الهيكل',
          startDate: d(2026, 5, 10),
          endDate: d(2026, 7, 25),
          progress: 30,
          status: 'delayed',
          amount: 165000,
          totalPayments: 50000,
          dependsOnIds: [301],
          notes: 'تأخر بسبب توريد البلوك.',
        },
        {
          id: 303,
          name: 'مقاول السقالات',
          contractorType: 'سقالات',
          zone: 'الهيكل',
          startDate: d(2026, 5, 1),
          endDate: d(2026, 8, 10),
          progress: 40,
          status: 'in_progress',
          amount: 95000,
          totalPayments: 40000,
        },
      ],
    },
    {
      id: 4,
      name: 'مرحلة التشطيبات والخدمات',
      description: 'الكهرباء والسباكة والتكييف والدهانات',
      order: 4,
      startDate: d(2026, 7, 1),
      endDate: d(2026, 11, 30),
      progress: 10,
      expanded: true,
      contractors: [
        {
          id: 401,
          name: 'مقاول الكهرباء',
          contractorType: 'كهرباء',
          zone: 'الدور الأول',
          startDate: d(2026, 7, 1),
          endDate: d(2026, 9, 15),
          progress: 25,
          status: 'in_progress',
          amount: 175000,
          totalPayments: 50000,
          dependsOnIds: [302],
        },
        {
          id: 402,
          name: 'مقاول التكييف',
          contractorType: 'تكييف',
          zone: 'الدور الأول',
          startDate: d(2026, 7, 20),
          endDate: d(2026, 9, 30),
          progress: 15,
          status: 'in_progress',
          amount: 220000,
          totalPayments: 60000,
          dependsOnIds: [401],
          notes: 'يوجد تداخل في زمن العمل مع مقاول الكهرباء.',
        },
        {
          id: 403,
          name: 'مقاول السباكة',
          contractorType: 'سباكة',
          zone: 'الدور الأرضي',
          startDate: d(2026, 8, 1),
          endDate: d(2026, 10, 15),
          progress: 5,
          status: 'in_progress',
          amount: 145000,
          totalPayments: 20000,
        },
        {
          id: 404,
          name: 'مقاول الدهانات',
          contractorType: 'دهانات',
          zone: 'الدور الأرضي',
          startDate: d(2026, 9, 15),
          endDate: d(2026, 11, 30),
          progress: 0,
          status: 'not_started',
          amount: 130000,
          totalPayments: 0,
          dependsOnIds: [403],
        },
      ],
    },
    {
      id: 5,
      name: 'مرحلة التسليم والتنظيف',
      description: 'الفحص النهائي والتسليم للمالك',
      order: 5,
      startDate: d(2026, 11, 15),
      endDate: d(2026, 12, 30),
      progress: 0,
      expanded: false,
      contractors: [
        {
          id: 501,
          name: 'مقاول التنظيف النهائي',
          contractorType: 'تنظيف',
          zone: 'كامل الموقع',
          startDate: d(2026, 11, 15),
          endDate: d(2026, 12, 10),
          progress: 0,
          status: 'not_started',
          amount: 35000,
          totalPayments: 0,
        },
        {
          id: 502,
          name: 'مقاول التشطيب النهائي',
          contractorType: 'تشطيب',
          zone: 'كامل الموقع',
          startDate: d(2026, 12, 1),
          endDate: d(2026, 12, 30),
          progress: 0,
          status: 'not_started',
          amount: 70000,
          totalPayments: 0,
          dependsOnIds: [501],
        },
      ],
    },
  ];

  // Auto-compute statuses
  phases.forEach((p) => {
    p.contractors.forEach((c) => {
      if (!c.status) c.status = pickStatus(c.progress, c.endDate);
    });
  });

  return phases;
}
