import { Observable } from 'rxjs';
import { ReportRow, ReportSortConfig } from './report-common.model';
import { ReportExportFormat } from './report-export.model';

/**
 * The query emitted by the reporting component in server mode. The parent page
 * (or a {@link ReportDataSource}) translates it into a real API call.
 */
export interface ReportQuery {
  page: number;
  pageSize: number;
  search?: string;
  /** Transformed filter values keyed by filter key. */
  filters?: Record<string, unknown>;
  sort?: ReportSortConfig[];
  /** Active group field keys. */
  groups?: string[];
  /** Keys of the currently visible columns (lets the backend trim payloads). */
  visibleColumns?: string[];
}

/** The server-mode result envelope consumed by the reporting component. */
export interface ReportResult<T = ReportRow> {
  items: T[];
  totalCount: number;
  page: number;
  pageSize: number;
  /** Aggregates over the **full filtered** dataset, keyed by summary key. */
  summaries?: Record<string, number>;
}

/**
 * Optional abstraction so a report can be driven by an injectable data source
 * instead of `(filtersChanged)` wiring. `exportAll` lets large "all filtered"
 * exports be generated by the backend rather than streamed into the browser.
 */
export interface ReportDataSource<T = ReportRow> {
  load(query: ReportQuery): Observable<ReportResult<T>>;
  exportAll?(query: ReportQuery, format: ReportExportFormat): Observable<Blob>;
}
